name-template: '$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '⚙️ Enhancements'
    label: 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🔧 Maintenance'
    labels:
      - 'dependencies'
      - 'maintenance'
template: |
  ## Changes

  $CHANGES

  Contributors to this release: $CONTRIBUTORS
