# Generated by Django 2.1.11 on 2019-10-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0070_rename_meta_categories_to_meta_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningstatus',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
